repos:
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.0'
    hooks:
    -   id: flake8
        exclude: tests/

# this requires pip3 install bandit
# repo fails to run correctly
-   repo: local
    hooks:
    -   id: python-bandit-vulnerability-check
        entry: bandit
        name: bandit
        args: [-l, -x, "usr/local/pproxy/tests/"]
        language: system
        files: ''

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
    -   id: python-safety-dependencies-check

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
#    -   id: detect-aws-credentials
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: debug-statements


